# Common configuration shared by all services

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
    com:
      taskify: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,refresh,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: when_authorized
  health:
    diskspace:
      enabled: false
    db:
      enabled: false
    redis:
      enabled: false
    circuitbreakers:
      enabled: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

# Service registry for inter-service communication
services:
  iam:
    name: iam-service
    url: lb://iam-service
  auth:
    name: auth-service
    url: lb://auth-service
  org:
    name: organization-service
    url: lb://organization-service

# Centralized RabbitMQ Event Configuration
rabbitmq:
  # Exchange definitions
  exchange:
    user-events: taskify.user.events
    membership-events: taskify.membership.events
    organization-events: taskify.organization.events

  routing-key:
    user-created: user.created
    user-deleted: user.deleted
    membership-added: membership.added
    membership-removed: membership.removed
    membership-role-updated: membership.role.updated
    organization-created: organization.created
    organization-updated: organization.updated
    organization-deleted: organization.deleted

  # Queue definitions for all services
  queue:
    # IAM Service queues
    iam-user-created: taskify.iam.user.created
    iam-user-deleted: taskify.iam.user.deleted
    iam-membership-added: taskify.iam.membership.added
    iam-membership-removed: taskify.iam.membership.removed
    iam-membership-role-updated: taskify.iam.membership.role.updated
    iam-organization-created: taskify.iam.organization.created
    iam-organization-updated: taskify.iam.organization.updated
    iam-organization-deleted: taskify.iam.organization.deleted

    # Organization Service queues
    org-user-created: taskify.org.user.created
    org-user-deleted: taskify.org.user.deleted
