eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

log4j:
    logger:
        org:
            hibernate:
                SQL: debug

logging:
    level:
        root: INFO
        org:
            hibernate:
                SQL: DEBUG
        com:
            taskify: DEBUG

spring:
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
        livereload:
            enabled: true

services:
    iam:
        name: iam-service
        url: lb://iam-service
    auth:
        name: auth-service
        url: lb://auth-service
    org:
        name: organization-service
        url: lb://organization-service
