server:
    port: 8084

spring:
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: thaitoan2311
    data:
        neo4j:
            database: neo4j

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env,loggers,refresh,prometheus,circuitbreakers
    endpoint:
        health:
            show-details: when_authorized
    health:
        diskspace:
            enabled: false
        db:
            enabled: false
        redis:
            enabled: false
        circuitbreakers:
            enabled: false
