server:
  port: 8084

spring:
  application:
    name: iam-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: "{cipher}729a31a826d75eddd793b02e382dc0bd7f6a5e8e8bbb7476838aa8fc410aa6a1"
  data:
    neo4j:
      database: neo4j
