server:
  port: 8086

spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_organization
    username: postgres
    password: "{cipher}729a31a826d75eddd793b02e382dc0bd7f6a5e8e8bbb7476838aa8fc410aa6a1"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      iam-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
