server:
    port: 8086

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/task_organization
        username: postgres
        password: thaitoan2311
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env,loggers,refresh,prometheus
    endpoint:
        health:
            show-details: when_authorized
    health:
        diskspace:
            enabled: true
        db:
            enabled: true
