server:
  port: 8087

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_project
    username: postgres
    password: "{cipher}c4ddfcc6d3e84d7db5a41a09bddfa43bdd9b3842fa89b65866d5a9d0f41cd5b8"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      iam-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
