server:
    port: 8082

spring:
    datasource:
        postgres:
            url: jdbc:postgresql://localhost:5432/task_project
            username: postgres
            password: thaitoan2311
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: taskify
