server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/task_user
        username: postgres
        password: thaitoan2311
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
