server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:testdb-project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: "{cipher}33809d139a985d3cb441b51983e605eb17c10d25c8c2bc9985ece7b959ceca4aa22042b69491ea1c41d79d9dc5b27629"
    expiration: 86400000
  refresh-token:
    expiration: 86400000
