server:
  port: 8082

spring:
  application:
    name: iam-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: "{cipher}c4ddfcc6d3e84d7db5a41a09bddfa43bdd9b3842fa89b65866d5a9d0f41cd5b8"
  data:
    neo4j:
      database: neo4j
